### ISSUE TITLE
Export sqlite_crdt.dart to separate package

### ISSUE THREAD

**Issue by tijanirf** [cachapa/tudo#22]
Hi @cachapa , 

First, I would like to thank you for a great CRDT example on Flutter, really appreciate the hard work.

Anyway, is there any plan to export `sqlite_crdt.dart` implementation to a separate dart package in the pub.dev? Personally, I would like to use it on my projects. I will gladly help if there's anything that needs to be done to achieve that, thank you 🙏

**Comment by cachapa** [comment]
Thanks for the feedback!

You have good timing, I'm just working on that (and refactoring `tudo` to use the external package instead).
Unfortunately it's not yet ready to release, but expect to find it in a couple of days in https://github.com/cachapa/sqlite_crdt

**Comment by cachapa** [comment]
Ok I decided to just publish it, since it was essentially ready: https://pub.dev/packages/sqlite_crdt

Beware that it's poorly tested - the code is completely rewritten from what's in `tudo`.

My goal is to migrate the app and use that as a live test for the package.

**Comment by tijanirf** [comment]
Thanks a lot, @cachapa. Really appreciate it.
