### ISSUE TITLE
Allow configuring server url

### ISSUE THREAD

**Issue by cachapa** [cachapa/tudo#26]
1. Show server configuration page on first launch (default to official server)
2. Allow changing server in settings

Challenge: figure out how to handle auth when changing servers in a running system

**Comment by bo0tzz** [comment]
I don't know how feasible this is, but would it be an idea to make the server per-list, with a global default setting? That way I could seamlessly share lists on my server with friends that are otherwise using the default server, and such.

**Comment by cachapa** [comment]
That's not really feasible with the current architecture, and would be a major pain to make the necessary changes.

It would also introduce a lot of complexity in the UI, which goes against the design goal of having a minimalist to-do app.

**Comment by bo0tzz** [comment]
Sounds fair!

**Comment by cachapa** [comment]
By the way, server configuration became a lot easier to implement with the recent account recovery changes.

The app now starts with a first-launch screen before it tries to connect.
The account key includes the backend URL, so by reading the QR code the user restores his complete session (server + key).

What's missing is de-hardcoding the official url in the app + the necessary UI elements to set a custom one.

**Comment by cachapa** [comment]
Released in 2.7.0 (Android is live, iOS whenever Apple decides).

It requires a complete app wipe though, as the server needs to be set before initializing sync.
I created issue #33 to track a more elegant way of migrating users.
