### ISSUE TITLE
Accidental swipe-deletes

### ISSUE THREAD

**Issue by bo0tzz** [cachapa/tudo#31]
I use android's gesture navigation, which includes swiping from the edge of the screen to navigate backwards. Occasionally, I miss and accidentally delete a list item. Luckily there is an undo button, but this is still inconvenient. I think there are a few possible approaches here:
1. Adding an option to the app that disables swipe-deletes altogether.
2. Having swipe-delete require an extra confirmation.
3. Adding a 'deadzone' to the ends of the swipe-delete area, so that it doesn't trigger when you swipe near the edge of the screen.
4. Using the [Gesture Exclusion API](https://developer.android.com/codelabs/gesture-navigation) - I don't actually know if/how this would work, but it seems like it's relevant here?
5. Just not missing ;)

**Comment by cachapa** [comment]
This is a general UX problem with Android (and iOS, to a certain extent).
All of the proposed solutions are kind of not ideal. Maybe 3 could work, but it's probably not so easy to implement.

I do like the swipe-to-delete gesture though, and would prefer to keep it.

I've been thinking of removing the undo bar that pops up and replacing it with a "trash" page which would show all deleted items from the last N days.
To me that solves the common issue of the bottom items being obscured by the popup, and the problem of only having a few seconds to click the undo button.

**Comment by bo0tzz** [comment]
I like that!

**Comment by bo0tzz** [comment]
Resolved with https://github.com/cachapa/tudo/commit/359ca2f287987da973194c095b29925a46f48522

Love how that came out, thank you!
